events {}

http {
    include /etc/nginx/mime.types;
    gzip on;
    gzip_types text/plain text/css application/javascript application/json;
    gzip_min_length 1024;
    limit_req_zone $binary_remote_addr zone=general:10m rate=10r/s;
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        add_header Permissions-Policy "geolocation=(), camera=(), microphone=()" always;
        add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self';" always;

        add_header Cache-Control "no-cache, must-revalidate" always;
        location ~* \.(js|css|png|jpg|woff2|mp4)$ {
            add_header Cache-Control "public, max-age=31536000, immutable" always;
            }
        location / {
            try_files $uri $uri/ /index.html;
            }
            error_page 404 /404.html;
            limit_req zone=general burst=20 nodelay;
            limit_req_status 429;
        location ~ /\. {
            deny all;
            return 404;
            }

        location ~* \.(env|git|yml|yaml|config)$ {
        deny all;
        return 404;
        }
    }
}